Broke a circular import trigged by the user manual compilation.
The error from running 'scons user_manual_pdf' was:

scons: *** [fetch_docstrings] ImportError : cannot import name fill_object_contents
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/SCons/Action.py", line 1046, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/data/relax/branches/uf_redesign/scons/manuals.py", line 471, in fetch_docstrings
    from docs.latex.fetch_docstrings import Fetch_docstrings
  File "/data/relax/branches/uf_redesign/docs/latex/fetch_docstrings.py", line 34, in <module>
    from user_functions.data import Uf_info; uf_info = Uf_info()
  File "/data/relax/branches/uf_redesign/user_functions/__init__.py", line 85, in <module>
    import user_functions.align_tensor
  File "/data/relax/branches/uf_redesign/user_functions/align_tensor.py", line 28, in <module>
    from generic_fns import align_tensor, pipes
  File "/data/relax/branches/uf_redesign/generic_fns/align_tensor.py", line 35, in <module>
    from angles import wrap_angles
  File "/data/relax/branches/uf_redesign/generic_fns/angles.py", line 32, in <module>
    from generic_fns import pipes
  File "/data/relax/branches/uf_redesign/generic_fns/pipes.py", line 32, in <module>
    from data import Relax_data_store; ds = Relax_data_store()
  File "/data/relax/branches/uf_redesign/data/__init__.py", line 36, in <module>
    from pipe_container import PipeContainer
  File "/data/relax/branches/uf_redesign/data/pipe_container.py", line 28, in <module>
    from align_tensor import AlignTensorList
  File "/data/relax/branches/uf_redesign/data/align_tensor.py", line 31, in <module>
    from data_classes import Element
  File "/data/relax/branches/uf_redesign/data/data_classes.py", line 32, in <module>
    from relax_xml import fill_object_contents, xml_to_object
  File "/data/relax/branches/uf_redesign/data/relax_xml.py", line 44, in <module>
    import arg_check
  File "/data/relax/branches/uf_redesign/arg_check.py", line 39, in <module>
    from relax_io import DummyFileObject
  File "/data/relax/branches/uf_redesign/relax_io.py", line 50, in <module>
    from generic_fns.mol_res_spin import generate_spin_id_data_array, spin_id_to_data_list
  File "/data/relax/branches/uf_redesign/generic_fns/mol_res_spin.py", line 47, in <module>
    from data.mol_res_spin import MoleculeContainer, ResidueContainer, SpinContainer
  File "/data/relax/branches/uf_redesign/data/mol_res_spin.py", line 36, in <module>
    from relax_xml import fill_object_contents, object_to_xml, xml_to_object
ImportError: cannot import name fill_object_contents
scons: building terminated because of errors.