Fixing a bug for running scons.
This happens after a: pip install -U numpy

Where numpy is upgraded from 13.3 to 16.1.0

The scons error was:
--------------------
scons: Reading SConscript files ...
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation:
  File "/home/travis/build/nmr-relax/relax/sconstruct", line 39:
    from scons.distrib import package, gpg_sign
  File "/home/travis/build/nmr-relax/relax/scons/distrib.py", line 34:
    from version import version
  File "/home/travis/build/nmr-relax/relax/version.py", line 34:
    import lib.structure.internal.object
  File "/home/travis/build/nmr-relax/relax/lib/structure/internal/object.py", line 47:
    from lib.structure.internal.displacements import Displacements
  File "/home/travis/build/nmr-relax/relax/lib/structure/internal/displacements.py", line 28:
    from lib.structure.internal.models import ModelContainer
  File "/home/travis/build/nmr-relax/relax/lib/structure/internal/models.py", line 30:
    from lib.structure.internal.molecules import MolList
  File "/home/travis/build/nmr-relax/relax/lib/structure/internal/molecules.py", line 35:
    from lib.xml import fill_object_contents, xml_to_object
  File "/home/travis/build/nmr-relax/relax/lib/xml.py", line 31:
    set_printoptions(precision=15, threshold=nan)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 246:
    floatmode, legacy)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/numpy/core/arrayprint.py", line 93:
    raise ValueError("threshold must be numeric and non-NAN, try "

More to read here:
* https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.set_printoptions.html
* https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array
* https://github.com/numpy/numpy/pull/12353