Added travis-ci support for Python 3.7 and OSX. Adding notifications from builds@travis-ci.com to nmr-relax-devel@lists.sourceforge.net
This is after inspiration from:
 https://github.com/WeblateOrg/translation-finder/blob/master/.travis.yml

Windows can not be added due to unknown compile error:

Building the relaxation curve fitting module target_functions\relax_fit.pyd
cl /Fotarget_functions\c_chi2.obj /c target_functions\c_chi2.c /nologo
/I"C:\Python27\include"
c_chi2.c
cl /Fotarget_functions\exponential.obj /c
target_functions\exponential.c /nologo /I"C:\Python27\include"
exponential.c
cl /Fotarget_functions\exponential_inv.obj /c
target_functions\exponential_inv.c /nologo /I"C:\Python27\include"
exponential_inv.c
cl /Fotarget_functions\exponential_sat.obj /c
target_functions\exponential_sat.c /nologo /I"C:\Python27\include"
exponential_sat.c
cl /Fotarget_functions\relax_fit.obj /c target_functions\relax_fit.c
/nologo /I"C:\Python27\include"
relax_fit.c
link /nologo /dll /out:target_functions\relax_fit.pyd
/implib:target_functions\relax_fit.lib /LIBPATH:C:\Python27\libs
target_functions\c_chi2.obj target_functions\exponential.obj
target_functions\exponential_inv.obj
target_functions\exponential_sat.obj target_functions\relax_fit.obj
   Creating library target_functions\relax_fit.lib and object
target_functions\relax_fit.exp
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyFloat_FromDouble referenced in function _param_to_c
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyFloat_AsDouble referenced in function _setup
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyList_New referenced in function _param_to_c
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyList_SetItem referenced in function _param_to_c
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyList_Append referenced in function _param_to_c
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyArg_ParseTuple referenced in function _param_to_c
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PyArg_ParseTupleAndKeywords referenced in function _setup
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__Py_InitModule4 referenced in function _initrelax_fit
relax_fit.obj : error LNK2019: unresolved external symbol
__imp__PySequence_GetItem referenced in function _setup
relax_fit.obj : error LNK2019: unresolved external symbol
__imp___Py_NoneStruct referenced in function _setup
C:\Python27\libs\python27.lib : warning LNK4272: library machine type
'x64' conflicts with target machine type 'x86'
target_functions\relax_fit.pyd : fatal error LNK1120: 10 unresolved externals
scons: building terminated because of errors.
scons: *** [target_functions\relax_fit.pyd] Error 1120