Syntax error fix for one of the unused scripts in the relax test suite shared data directories.
This problem was encountered by Jack Howarth <howarth att bromo dott med dott uc dott edu> and
communicated in a private message.  The issue was found by fink.  This script is never used and will
never be used again - it is only there for reference.  How a syntax error was introduced is a
mystery.  For reference, the full message is:

"""
   While preparing fink packaging for the new relax 3.0.0 release, I noticed an error
in the python scripts. When installing relax-py27-3.0.0, I get the following error as
the the frame_order_pseudo_ellipse.py python script is compiled. What is the correct
syntax for that particular call to pymol.command?

Setting up relax-py27 (3.0.0-1) ...
Compiling /sw/lib/relax-py27/test_suite/shared_data/frame_order/cam/pseudo_ellipse_free_rotor/frame_order_pseudo_ellipse.py ...
  File "/sw/lib/relax-py27/test_suite/shared_data/frame_order/cam/pseudo_ellipse_free_rotor/frame_order_pseudo_ellipse.py", line 154
    pymol.command('show spheres'_pseudo_ellipse)
                                              ^
SyntaxError: invalid syntax

Thanks in advance for any clarification.
"""